apiVersion: v2
description: Helm Chart for Docker example-voting-app
name: example-voting-app
keywords:
- codefresh
- kubernetes
- example-voting-app
version: 2.0.0

dependencies:
- name: postgresql
  version: ~10.3.13
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
  
- name: redis
  version: ~12.9.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled
  
- name: result
  version: 1.0.0
  repository: file://local-charts/result
  
- name: vote
  version: 1.0.0
  repository: file://local-charts/vote
  
- name: worker
  version: 1.0.0
  repository: file://local-charts/worker