# Default values for worker.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: drwarner/example-voting-app-worker
  tag: demo

postgresql:
  postgresUser: postgres
  postgresPassword: postgres

redis:
  usePassword: false

replicaCount: 1
