apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-voting-app
spec:
  destination:
    name: in-cluster
    namespace: example-voting-app
    server: ''
  source:
    path: .
    repoURL: 'https://github.com/drwarner/k8s-example-voting-app'
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
      releaseName: example-voting-app
  
  project: default
