# Default values for vote.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value
image: 
  repository: drwarner/example-voting-app-vote
  tag: demo

redis:
  usePassword: false

replicaCount: 1
